name: My actions have consequence
on: [push]
jobs:
  ega:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
          # Optional: if your chrome binary name is different
          chromeapp: chrome
      - name: install selenium
        run: pip install selenium
      - run: python main.py
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
