name: My actions have consequence
on: [push]
jobs:
  ega:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: install selenium
        run: pip install selenium
      - run: python main.py
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
